postgres:
  container_name: postgres_container
  image: postgres
  environment:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'password'
    PGDATA: /data/postgres
  volumes:
    - postgres:/data/postgres
  ports:
    - "5432:5432"
  networks:
    - postgres
  restart: unless-stopped
