version: '2.4'

services:
  postgres:
    restart: unless-stopped
    container_name: postgres_container
    image: postgres:12
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbitmq

networks:
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge
volumes:
  postgres:
  rabbitmq:
